// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUzEWImw6KkQDb2QtiG3utIs0O5tQoQs',
    appId: '1:59485619839:web:8cd7d0da406909293c614a',
    messagingSenderId: '59485619839',
    projectId: 'futurama1111',
    authDomain: 'futurama1111.firebaseapp.com',
    storageBucket: 'futurama1111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXwwxchbBcu480eftVlsNfUAZlQJ-1Hk',
    appId: '1:59485619839:android:1199d9e1a77ec8c03c614a',
    messagingSenderId: '59485619839',
    projectId: 'futurama1111',
    storageBucket: 'futurama1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3emTi6ZDnZS5A0FrjKuCGm0sYP-fDWVM',
    appId: '1:59485619839:ios:dd1aac858fae6bfb3c614a',
    messagingSenderId: '59485619839',
    projectId: 'futurama1111',
    storageBucket: 'futurama1111.firebasestorage.app',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3emTi6ZDnZS5A0FrjKuCGm0sYP-fDWVM',
    appId: '1:59485619839:ios:dd1aac858fae6bfb3c614a',
    messagingSenderId: '59485619839',
    projectId: 'futurama1111',
    storageBucket: 'futurama1111.firebasestorage.app',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUzEWImw6KkQDb2QtiG3utIs0O5tQoQs',
    appId: '1:59485619839:web:a475b3bbf3ef172f3c614a',
    messagingSenderId: '59485619839',
    projectId: 'futurama1111',
    authDomain: 'futurama1111.firebaseapp.com',
    storageBucket: 'futurama1111.firebasestorage.app',
  );
}
